/**
 * screens-v25.cjs — v2.5 feature screenshots (Phase E).
 *
 * Reuses the fixtures generated by the e2e run (docs/screenshots/e2e_*.wav,
 * e2e_cover_wide.png) and the interaction patterns from scripts/e2e.cjs.
 * Run AFTER `npm run dev` on :3100 and AFTER the e2e suite finished
 * (a concurrent Chrome would skew the FPS gate).
 *
 *   node scripts/screens-v25.cjs [http://127.0.0.1:3100/]
 *
 * Shots land in docs/screenshots/v25_*.png. Each shot is best-effort: a
 * failing step is logged and the script continues; exit 0 only when all 12
 * files were written.
 */
const puppeteer = require('puppeteer-core');
const path = require('path');
const fs = require('fs');

const EDGE = process.env.NMP_BROWSER || 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const APP_URL = process.argv[2] || 'http://127.0.0.1:3100/';
const OUT = path.join(__dirname, '..', 'docs', 'screenshots');

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function waitFor(page, fn, ms = 20000, step = 300) {
  const t0 = Date.now();
  while (Date.now() - t0 < ms) {
    try { if (await page.evaluate(fn)) return true; } catch { /* mid-nav */ }
    await sleep(step);
  }
  return false;
}

let shots = 0;
const missing = [];
async function shot(page, name) {
  const file = path.join(OUT, `${name}.png`);
  try {
    await page.screenshot({ path: file });
    shots += 1;
    console.log(`  SHOT  ${name}.png`);
  } catch (e) {
    missing.push(name);
    console.log(`  MISS  ${name}: ${e.message}`);
  }
}

// Scroll the first element whose text contains `needle` into view (centered).
async function scrollToText(page, needle) {
  return page.evaluate((s) => {
    const els = [...document.querySelectorAll('h1,h2,h3,h4,h5,div,span,p')];
    const el = els.find((x) => x.childElementCount === 0 && x.textContent.toUpperCase().includes(s));
    if (!el) return false;
    el.scrollIntoView({ block: 'center' });
    return true;
  }, needle.toUpperCase());
}

(async () => {
  const browser = await puppeteer.launch({
    executablePath: EDGE,
    headless: 'new',
    args: ['--no-sandbox', '--disable-gpu', '--autoplay-policy=no-user-gesture-required'],
    defaultViewport: { width: 1440, height: 900 },
  });
  const page = await browser.newPage();
  const errs = [];
  page.on('console', (m) => { if (['error', 'warning'].includes(m.type())) errs.push(m.text().slice(0, 140)); });
  page.on('pageerror', (e) => errs.push('pageerror: ' + String(e).slice(0, 140)));

  // Page helpers (copied from e2e.cjs — same semantics).
  await page.evaluateOnNewDocument(() => {
    const inputSet = (el, value) => {
      const proto = el.tagName === 'SELECT' ? window.HTMLSelectElement.prototype : window.HTMLInputElement.prototype;
      Object.getOwnPropertyDescriptor(proto, 'value').set.call(el, String(value));
      el.dispatchEvent(new Event(el.tagName === 'SELECT' ? 'change' : 'input', { bubbles: true }));
    };
    const clickText = (text) => {
      const b = [...document.querySelectorAll('button')].find((x) => x.textContent.trim().toUpperCase() === text.toUpperCase() && !x.disabled);
      if (!b) return false;
      b.click();
      return true;
    };
    const setFxSlider = (fxLabel, value) => {
      const grid = document.querySelector('div.grid.grid-cols-5');
      if (!grid) return { ok: false };
      const cell = [...grid.children].find((c) => c.textContent.trim().toUpperCase().startsWith(fxLabel.toUpperCase()));
      const range = cell && cell.querySelector('input[type="range"]');
      if (!range || range.disabled) return { ok: false };
      inputSet(range, value);
      return { ok: true };
    };
    window.__h = { inputSet, clickText, setFxSlider };
  });
  const h = (page, name, ...args) => page.evaluate((n, a) => window.__h[n](...a), name, args);

  console.log('load', APP_URL);
  await page.goto(APP_URL, { waitUntil: 'domcontentloaded' });
  if (!(await waitFor(page, () => !!document.querySelector('select'), 40000))) throw new Error('app did not mount');
  await sleep(1500);

  // Load the main tone fixture.
  const TONE = path.join(OUT, 'e2e_tone.wav');
  const COVER = path.join(OUT, 'e2e_cover_wide.png');
  const GUIDE = path.join(OUT, 'e2e_guide.wav');
  const DUB = path.join(OUT, 'e2e_dub.wav');
  const BATCH = [1, 2, 3].map((i) => path.join(OUT, `e2e_batch${i}.wav`));
  const trackInput = await page.$('#track-upload');
  if (!trackInput) throw new Error('#track-upload not found');
  await trackInput.uploadFile(TONE);
  await waitFor(page, () => document.querySelectorAll('input[type="range"]').length > 10, 30000);
  const ready = await waitFor(page, () => /PROCESSING:\s*READY/i.test(document.body.innerText), 90000);
  console.log('engine ready:', ready);
  await sleep(1200);

  // -- 1. Pro chain top ------------------------------------------------------
  await page.evaluate(() => window.scrollTo(0, 0));
  const scroller = await page.evaluateHandle(() => {
    const els = [...document.querySelectorAll('div')].filter((d) => d.scrollHeight > d.clientHeight + 40 && d.clientHeight > 300);
    return els.sort((a, b) => b.scrollHeight - a.scrollHeight)[0] || window;
  });
  await page.evaluate((el) => { if (el && el.scrollTo) el.scrollTo(0, 0); }, scroller);
  await shot(page, 'v25_pro_chain');

  // -- 2. Parametric EQ -------------------------------------------------------
  await scrollToText(page, 'PARAMETRIC EQ');
  await sleep(400);
  await shot(page, 'v25_peq');

  // -- 3. Stem Studio: Vocal solo --------------------------------------------
  await h(page, 'clickText', 'VOCAL');
  await sleep(300);
  await page.evaluate(() => {
    const b = document.querySelector('[data-testid="stem-solo"]');
    if (b && !b.disabled) b.click();
  });
  await sleep(400);
  await page.evaluate(() => {
    const b = document.querySelector('[data-testid="stem-solo"]');
    if (b) b.scrollIntoView({ block: 'center' });
  });
  await sleep(300);
  await shot(page, 'v25_stems_solo');
  // Solo off afterwards (keeps later shots honest).
  await page.evaluate(() => { const b = document.querySelector('[data-testid="stem-solo"]'); if (b) b.click(); });

  // -- 4. Vocal Align (guide + dub loaded, aligned) ---------------------------
  if (fs.existsSync(GUIDE) && fs.existsSync(DUB)) {
    const gIn = await page.$('input[data-testid="align-guide-input"]');
    const dIn = await page.$('input[data-testid="align-dub-input"]');
    if (gIn && dIn) {
      await page.evaluate(() => {
        const b = document.querySelector('[data-testid="align-apply"]');
        if (b) b.scrollIntoView({ block: 'center' });
      });
      await gIn.uploadFile(GUIDE);
      await sleep(900);
      await dIn.uploadFile(DUB);
      await sleep(900);
      await page.evaluate(() => document.querySelector('[data-testid="align-apply"]').click());
      await waitFor(page, () => !!document.querySelector('[data-testid="align-dl-aligned"]'), 60000);
      await sleep(400);
      await shot(page, 'v25_vocal_align');
    } else {
      missing.push('v25_vocal_align (inputs not found)');
    }
  } else {
    missing.push('v25_vocal_align (fixtures missing)');
  }

  // -- 5. FX automation region -------------------------------------------------
  await h(page, 'clickText', '+ ADD FX REGION');
  await sleep(500);
  await h(page, 'setFxSlider', 'Reverb', 90);
  await sleep(300);
  await page.evaluate(() => {
    const box = document.querySelector('div.max-h-\\[160px\\]');
    (box || document).scrollIntoView({ block: 'center' });
  });
  await sleep(300);
  await shot(page, 'v25_fx_automation');

  // -- 6. Cover drag ------------------------------------------------------------
  if (fs.existsSync(COVER)) {
    const coverInput = await page.$('#cover-upload');
    if (coverInput) {
      await coverInput.uploadFile(COVER);
      const aspectKnown = await waitFor(page, () => {
        const img = document.querySelector('img[alt="Cover Art"]');
        return !!(img && /translate\(/.test(img.style.transform || ''));
      }, 15000);
      if (aspectKnown) {
        const imgBox = await page.evaluate(() => {
          const img = document.querySelector('img[alt="Cover Art"]');
          img.scrollIntoView({ block: 'center' });
          const r = img.getBoundingClientRect();
          return { x: r.x, y: r.y, w: r.width, h: r.height };
        });
        await sleep(300);
        const cx = imgBox.x + imgBox.w / 2;
        const cy = imgBox.y + imgBox.h / 2;
        await page.mouse.move(cx, cy);
        await page.mouse.down();
        await page.mouse.move(cx + imgBox.w * 0.35, cy, { steps: 5 });
        await page.mouse.up();
        await sleep(300);
        await shot(page, 'v25_cover_drag');
      } else missing.push('v25_cover_drag (aspect not known)');
      await page.evaluate(() => window.__NMP__ && window.__NMP__.resetCoverOffset && window.__NMP__.resetCoverOffset());
    } else missing.push('v25_cover_drag (#cover-upload missing)');
  } else missing.push('v25_cover_drag (fixture missing)');

  // -- 7/8. Pexels selection (synthetic, offline) + visualizer frame ----------
  await page.evaluate(() => {
    const cb = [...document.querySelectorAll('input[type="checkbox"]')]
      .find((c) => c.parentElement.textContent.includes('Export Video'));
    if (cb && !cb.checked) cb.click();
  });
  await sleep(400);
  const clipUrls = await page.evaluate(async () => {
    const make = (style) => new Promise((resolve) => {
      const c = document.createElement('canvas');
      c.width = 320; c.height = 180;
      const cx = c.getContext('2d');
      cx.fillStyle = style; cx.fillRect(0, 0, 320, 180);
      let frame = 0;
      const tick = () => { frame += 1; cx.fillStyle = 'rgba(0,0,0,0.4)'; cx.fillRect((frame * 7) % 318, 0, 2, 2); };
      const stream = c.captureStream(30);
      const iv = setInterval(tick, 100);
      const rec = new MediaRecorder(stream, { mimeType: 'video/webm' });
      const chunks = [];
      rec.ondataavailable = (ev) => { if (ev.data && ev.data.size) chunks.push(ev.data); };
      rec.onstop = () => { clearInterval(iv); stream.getTracks().forEach((t) => t.stop()); resolve(URL.createObjectURL(new Blob(chunks, { type: 'video/webm' }))); };
      rec.start(250);
      setTimeout(() => rec.stop(), 1000);
    });
    const colors = ['rgb(220,20,30)', 'rgb(30,20,220)', 'rgb(20,180,80)', 'rgb(230,180,20)'];
    const urls = [];
    for (const c of colors) urls.push(await make(c));
    return urls;
  });
  await page.evaluate((urls) => {
    try {
      window.__NMP__.setPexelsTestSelection(
        urls.map((u, i) => ({ url: u, author: `Clip Author ${i + 1}` })));
    } catch { /* hook missing */ }
  }, clipUrls);
  await page.evaluate(() => {
    const radios = [...document.querySelectorAll('input[type="radio"][name="videoBgMode"]')];
    if (radios[1] && !radios[1].checked) radios[1].click();
  });
  await sleep(700);
  await page.evaluate(() => {
    const r = document.querySelector('input[type="radio"][name="videoBgMode"]');
    if (r) r.scrollIntoView({ block: 'center' });
  });
  await sleep(300);
  await shot(page, 'v25_pexels_select');

  // Frame of the composed background + cover: play the track so the
  // visualizer shows the selected clip behind the cover frame.
  await page.evaluate(() => {
    const b = [...document.querySelectorAll('button')].find((x) => /play/i.test(x.getAttribute('title') || ''))
      || [...document.querySelectorAll('svg.lucide-play')].map((s) => s.closest('button'))[0];
    if (b && !b.disabled) b.click();
  });
  await sleep(2500);
  await page.evaluate(() => {
    const cv = document.querySelector('canvas');
    if (cv) cv.scrollIntoView({ block: 'center' });
  });
  await sleep(500);
  await shot(page, 'v25_video_frame');
  await page.evaluate(() => {
    const b = [...document.querySelectorAll('svg.lucide-square')].map((s) => s.closest('button'))[0];
    if (b && !b.disabled) b.click();
  });

  // -- 9. Lite one-click report -------------------------------------------------
  await h(page, 'clickText', 'Lite');
  await sleep(1800);
  await page.evaluate(() => {
    const b = [...document.querySelectorAll('button')].find((x) =>
      x.textContent.trim().toUpperCase() === 'MASTER' && /px-5 py-2\.5/.test(x.className) && !x.disabled);
    if (b) b.scrollIntoView({ block: 'center' });
  });
  const clickedLite = await page.evaluate(() => {
    const b = [...document.querySelectorAll('button')].find((x) =>
      x.textContent.trim().toUpperCase() === 'MASTER' && /px-5 py-2\.5/.test(x.className) && !x.disabled);
    if (!b) return false;
    b.click();
    return true;
  });
  if (clickedLite) {
    await waitFor(page, () => /MASTERED/i.test(document.body.innerText), 90000);
    await sleep(600);
    await shot(page, 'v25_lite_report');
  } else missing.push('v25_lite_report (MASTER button)');

  // -- 10. Batch queue ------------------------------------------------------------
  const batchInput = await page.$('input[type="file"][multiple]');
  if (batchInput && BATCH.every((f) => fs.existsSync(f))) {
    await batchInput.uploadFile(...BATCH);
    await waitFor(page, () => document.body.innerText.includes('3/'), 15000);
    await h(page, 'clickText', 'Run');
    await sleep(20000); // progress lines mid-flight read better than idle
    await page.evaluate(() => {
      const box = [...document.querySelectorAll('div')].find((d) => d.querySelector('input[type="file"][multiple]'));
      if (box) box.scrollIntoView({ block: 'center' });
    });
    await sleep(300);
    await shot(page, 'v25_batch');
  } else missing.push('v25_batch (input/fixtures)');

  // -- 11/12. Languages ------------------------------------------------------------
  for (const lang of ['ES', 'JA']) {
    await h(page, 'clickText', lang);
    await sleep(900);
    await page.evaluate(() => window.scrollTo(0, 0));
    await sleep(300);
    await shot(page, `v25_lang_${lang.toLowerCase()}`);
  }
  await h(page, 'clickText', 'EN');
  await sleep(300);

  await browser.close();
  console.log(`\n${shots}/12 shots written` + (missing.length ? `; missing: ${missing.join(', ')}` : ''));
  if (errs.length) console.log('console noise:', errs.length, errs.slice(0, 5));
  process.exit(missing.length === 0 ? 0 : 1);
})().catch((e) => { console.error('FATAL', e); process.exit(2); });
